//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyrapchieuphim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public string IDDanhGiaPhim { get; set; }
        public string BinhLuan1 { get; set; }
        public Nullable<int> DanhGiaSao { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string IDNguoiDung { get; set; }
        public string IDPhim { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Phim Phim { get; set; }
    }
}
