<?xml version="1.0" encoding="utf-8"?><Database Name="Quanlyrapphim" Class="QuanlyrapphimDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.BinhLuan" Member="BinhLuans">
    <Type Name="BinhLuan">
      <Column Name="IDDanhGiaPhim" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BinhLuan" Member="BinhLuan1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DanhGiaSao" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGian" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDNguoiDung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDPhim" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NguoiDung_BinhLuan" Member="NguoiDung" ThisKey="IDNguoiDung" OtherKey="IDNguoiDung" Type="NguoiDung" IsForeignKey="true" />
      <Association Name="Phim_BinhLuan" Member="Phim" ThisKey="IDPhim" OtherKey="IDPhim" Type="Phim" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChoNgoi1" Member="ChoNgoi1s">
    <Type Name="ChoNgoi1">
      <Column Name="IDChoNgoi" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenChoNgoi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ChoNgoi1_Ve" Member="Ves" ThisKey="IDChoNgoi" OtherKey="IDChoNgoi" Type="Ve" />
    </Type>
  </Table>
  <Table Name="dbo.DichVu_Ve" Member="DichVu_Ves">
    <Type Name="DichVu_Ve">
      <Column Name="IDVe" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDDichVu" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DichVu1_DichVu_Ve" Member="DichVu1" ThisKey="IDDichVu" OtherKey="IDDichVu" Type="DichVu1" IsForeignKey="true" />
      <Association Name="Ve_DichVu_Ve" Member="Ve" ThisKey="IDVe" OtherKey="IDVe" Type="Ve" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DichVu1" Member="DichVu1s">
    <Type Name="DichVu1">
      <Column Name="IDDichVu" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDichVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="DichVu1_DichVu_Ve" Member="DichVu_Ves" ThisKey="IDDichVu" OtherKey="IDDichVu" Type="DichVu_Ve" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="IDHoaDon" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHoaDon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDVe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Ve_HoaDon" Member="Ve" ThisKey="IDVe" OtherKey="IDVe" Type="Ve" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="IDNguoiDung" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNguoiDung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenChucVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HashPass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quyen" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="NguoiDung_BinhLuan" Member="BinhLuans" ThisKey="IDNguoiDung" OtherKey="IDNguoiDung" Type="BinhLuan" />
      <Association Name="NguoiDung_Ve" Member="Ves" ThisKey="IDNguoiDung" OtherKey="IDNguoiDung" Type="Ve" />
    </Type>
  </Table>
  <Table Name="dbo.Phim" Member="Phims">
    <Type Name="Phim">
      <Column Name="IDPhim" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenPhim" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TheLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KhoiChieu" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NamSanXuat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DaoDien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DienVien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Phim_BinhLuan" Member="BinhLuans" ThisKey="IDPhim" OtherKey="IDPhim" Type="BinhLuan" />
      <Association Name="Phim_SuatChieu" Member="SuatChieus" ThisKey="IDPhim" OtherKey="IDPhim" Type="SuatChieu" />
    </Type>
  </Table>
  <Table Name="dbo.PhongChieu" Member="PhongChieus">
    <Type Name="PhongChieu">
      <Column Name="IDPhongChieu" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenPhongChieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiPhong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PhongChieu_SuatChieu" Member="SuatChieus" ThisKey="IDPhongChieu" OtherKey="IDPhongChieu" Type="SuatChieu" />
    </Type>
  </Table>
  <Table Name="dbo.SuatChieu" Member="SuatChieus">
    <Type Name="SuatChieu">
      <Column Name="IDSuatChieu" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSuatChieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayChieu" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThoiGianChieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDPhongChieu" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="IDPhim" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="SuatChieu_Ve" Member="Ves" ThisKey="IDSuatChieu" OtherKey="IDSuatChieu" Type="Ve" />
      <Association Name="Phim_SuatChieu" Member="Phim" ThisKey="IDPhim" OtherKey="IDPhim" Type="Phim" IsForeignKey="true" />
      <Association Name="PhongChieu_SuatChieu" Member="PhongChieu" ThisKey="IDPhongChieu" OtherKey="IDPhongChieu" Type="PhongChieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ve" Member="Ves">
    <Type Name="Ve">
      <Column Name="IDVe" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenVe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaVe" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDChoNgoi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDSuatChieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDNguoiDung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Ve_DichVu_Ve" Member="DichVu_Ves" ThisKey="IDVe" OtherKey="IDVe" Type="DichVu_Ve" />
      <Association Name="Ve_HoaDon" Member="HoaDons" ThisKey="IDVe" OtherKey="IDVe" Type="HoaDon" />
      <Association Name="ChoNgoi1_Ve" Member="ChoNgoi1" ThisKey="IDChoNgoi" OtherKey="IDChoNgoi" Type="ChoNgoi1" IsForeignKey="true" />
      <Association Name="NguoiDung_Ve" Member="NguoiDung" ThisKey="IDNguoiDung" OtherKey="IDNguoiDung" Type="NguoiDung" IsForeignKey="true" />
      <Association Name="SuatChieu_Ve" Member="SuatChieu" ThisKey="IDSuatChieu" OtherKey="IDSuatChieu" Type="SuatChieu" IsForeignKey="true" />
    </Type>
  </Table>
</Database>