#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyrapchieuphim.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Quanlyrapphim")]
	public partial class QuanlyrapphimDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBinhLuan(BinhLuan instance);
    partial void UpdateBinhLuan(BinhLuan instance);
    partial void DeleteBinhLuan(BinhLuan instance);
    partial void InsertChoNgoi1(ChoNgoi1 instance);
    partial void UpdateChoNgoi1(ChoNgoi1 instance);
    partial void DeleteChoNgoi1(ChoNgoi1 instance);
    partial void InsertDichVu_Ve(DichVu_Ve instance);
    partial void UpdateDichVu_Ve(DichVu_Ve instance);
    partial void DeleteDichVu_Ve(DichVu_Ve instance);
    partial void InsertDichVu1(DichVu1 instance);
    partial void UpdateDichVu1(DichVu1 instance);
    partial void DeleteDichVu1(DichVu1 instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertPhim(Phim instance);
    partial void UpdatePhim(Phim instance);
    partial void DeletePhim(Phim instance);
    partial void InsertPhongChieu(PhongChieu instance);
    partial void UpdatePhongChieu(PhongChieu instance);
    partial void DeletePhongChieu(PhongChieu instance);
    partial void InsertSuatChieu(SuatChieu instance);
    partial void UpdateSuatChieu(SuatChieu instance);
    partial void DeleteSuatChieu(SuatChieu instance);
    partial void InsertVe(Ve instance);
    partial void UpdateVe(Ve instance);
    partial void DeleteVe(Ve instance);
    #endregion
		
		public QuanlyrapphimDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanlyrapphimDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanlyrapphimDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanlyrapphimDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BinhLuan> BinhLuans
		{
			get
			{
				return this.GetTable<BinhLuan>();
			}
		}
		
		public System.Data.Linq.Table<ChoNgoi1> ChoNgoi1s
		{
			get
			{
				return this.GetTable<ChoNgoi1>();
			}
		}
		
		public System.Data.Linq.Table<DichVu_Ve> DichVu_Ves
		{
			get
			{
				return this.GetTable<DichVu_Ve>();
			}
		}
		
		public System.Data.Linq.Table<DichVu1> DichVu1s
		{
			get
			{
				return this.GetTable<DichVu1>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<Phim> Phims
		{
			get
			{
				return this.GetTable<Phim>();
			}
		}
		
		public System.Data.Linq.Table<PhongChieu> PhongChieus
		{
			get
			{
				return this.GetTable<PhongChieu>();
			}
		}
		
		public System.Data.Linq.Table<SuatChieu> SuatChieus
		{
			get
			{
				return this.GetTable<SuatChieu>();
			}
		}
		
		public System.Data.Linq.Table<Ve> Ves
		{
			get
			{
				return this.GetTable<Ve>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BinhLuan")]
	public partial class BinhLuan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDDanhGiaPhim;
		
		private string _BinhLuan1;
		
		private System.Nullable<int> _DanhGiaSao;
		
		private System.Nullable<System.DateTime> _ThoiGian;
		
		private string _IDNguoiDung;
		
		private string _IDPhim;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
		private EntityRef<Phim> _Phim;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDanhGiaPhimChanging(string value);
    partial void OnIDDanhGiaPhimChanged();
    partial void OnBinhLuan1Changing(string value);
    partial void OnBinhLuan1Changed();
    partial void OnDanhGiaSaoChanging(System.Nullable<int> value);
    partial void OnDanhGiaSaoChanged();
    partial void OnThoiGianChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianChanged();
    partial void OnIDNguoiDungChanging(string value);
    partial void OnIDNguoiDungChanged();
    partial void OnIDPhimChanging(string value);
    partial void OnIDPhimChanged();
    #endregion
		
		public BinhLuan()
		{
			this._NguoiDung = default(EntityRef<NguoiDung>);
			this._Phim = default(EntityRef<Phim>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDanhGiaPhim", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDDanhGiaPhim
		{
			get
			{
				return this._IDDanhGiaPhim;
			}
			set
			{
				if ((this._IDDanhGiaPhim != value))
				{
					this.OnIDDanhGiaPhimChanging(value);
					this.SendPropertyChanging();
					this._IDDanhGiaPhim = value;
					this.SendPropertyChanged("IDDanhGiaPhim");
					this.OnIDDanhGiaPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="BinhLuan", Storage="_BinhLuan1", DbType="NVarChar(50)")]
		public string BinhLuan1
		{
			get
			{
				return this._BinhLuan1;
			}
			set
			{
				if ((this._BinhLuan1 != value))
				{
					this.OnBinhLuan1Changing(value);
					this.SendPropertyChanging();
					this._BinhLuan1 = value;
					this.SendPropertyChanged("BinhLuan1");
					this.OnBinhLuan1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhGiaSao", DbType="Int")]
		public System.Nullable<int> DanhGiaSao
		{
			get
			{
				return this._DanhGiaSao;
			}
			set
			{
				if ((this._DanhGiaSao != value))
				{
					this.OnDanhGiaSaoChanging(value);
					this.SendPropertyChanging();
					this._DanhGiaSao = value;
					this.SendPropertyChanged("DanhGiaSao");
					this.OnDanhGiaSaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNguoiDung", DbType="NVarChar(50)")]
		public string IDNguoiDung
		{
			get
			{
				return this._IDNguoiDung;
			}
			set
			{
				if ((this._IDNguoiDung != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._IDNguoiDung = value;
					this.SendPropertyChanged("IDNguoiDung");
					this.OnIDNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPhim", DbType="NVarChar(50)")]
		public string IDPhim
		{
			get
			{
				return this._IDPhim;
			}
			set
			{
				if ((this._IDPhim != value))
				{
					if (this._Phim.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDPhimChanging(value);
					this.SendPropertyChanging();
					this._IDPhim = value;
					this.SendPropertyChanged("IDPhim");
					this.OnIDPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_BinhLuan", Storage="_NguoiDung", ThisKey="IDNguoiDung", OtherKey="IDNguoiDung", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.BinhLuans.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.BinhLuans.Add(this);
						this._IDNguoiDung = value.IDNguoiDung;
					}
					else
					{
						this._IDNguoiDung = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_BinhLuan", Storage="_Phim", ThisKey="IDPhim", OtherKey="IDPhim", IsForeignKey=true)]
		public Phim Phim
		{
			get
			{
				return this._Phim.Entity;
			}
			set
			{
				Phim previousValue = this._Phim.Entity;
				if (((previousValue != value) 
							|| (this._Phim.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phim.Entity = null;
						previousValue.BinhLuans.Remove(this);
					}
					this._Phim.Entity = value;
					if ((value != null))
					{
						value.BinhLuans.Add(this);
						this._IDPhim = value.IDPhim;
					}
					else
					{
						this._IDPhim = default(string);
					}
					this.SendPropertyChanged("Phim");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChoNgoi1")]
	public partial class ChoNgoi1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDChoNgoi;
		
		private string _TenChoNgoi;
		
		private EntitySet<Ve> _Ves;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChoNgoiChanging(string value);
    partial void OnIDChoNgoiChanged();
    partial void OnTenChoNgoiChanging(string value);
    partial void OnTenChoNgoiChanged();
    #endregion
		
		public ChoNgoi1()
		{
			this._Ves = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves), new Action<Ve>(this.detach_Ves));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChoNgoi", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDChoNgoi
		{
			get
			{
				return this._IDChoNgoi;
			}
			set
			{
				if ((this._IDChoNgoi != value))
				{
					this.OnIDChoNgoiChanging(value);
					this.SendPropertyChanging();
					this._IDChoNgoi = value;
					this.SendPropertyChanged("IDChoNgoi");
					this.OnIDChoNgoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChoNgoi", DbType="NVarChar(50)")]
		public string TenChoNgoi
		{
			get
			{
				return this._TenChoNgoi;
			}
			set
			{
				if ((this._TenChoNgoi != value))
				{
					this.OnTenChoNgoiChanging(value);
					this.SendPropertyChanging();
					this._TenChoNgoi = value;
					this.SendPropertyChanged("TenChoNgoi");
					this.OnTenChoNgoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChoNgoi1_Ve", Storage="_Ves", ThisKey="IDChoNgoi", OtherKey="IDChoNgoi")]
		public EntitySet<Ve> Ves
		{
			get
			{
				return this._Ves;
			}
			set
			{
				this._Ves.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.ChoNgoi1 = this;
		}
		
		private void detach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.ChoNgoi1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DichVu_Ve")]
	public partial class DichVu_Ve : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDVe;
		
		private string _IDDichVu;
		
		private EntityRef<DichVu1> _DichVu1;
		
		private EntityRef<Ve> _Ve;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDVeChanging(string value);
    partial void OnIDVeChanged();
    partial void OnIDDichVuChanging(string value);
    partial void OnIDDichVuChanged();
    #endregion
		
		public DichVu_Ve()
		{
			this._DichVu1 = default(EntityRef<DichVu1>);
			this._Ve = default(EntityRef<Ve>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDVe", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDVe
		{
			get
			{
				return this._IDVe;
			}
			set
			{
				if ((this._IDVe != value))
				{
					if (this._Ve.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDVeChanging(value);
					this.SendPropertyChanging();
					this._IDVe = value;
					this.SendPropertyChanged("IDVe");
					this.OnIDVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDichVu", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDDichVu
		{
			get
			{
				return this._IDDichVu;
			}
			set
			{
				if ((this._IDDichVu != value))
				{
					if (this._DichVu1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDichVuChanging(value);
					this.SendPropertyChanging();
					this._IDDichVu = value;
					this.SendPropertyChanged("IDDichVu");
					this.OnIDDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu1_DichVu_Ve", Storage="_DichVu1", ThisKey="IDDichVu", OtherKey="IDDichVu", IsForeignKey=true)]
		public DichVu1 DichVu1
		{
			get
			{
				return this._DichVu1.Entity;
			}
			set
			{
				DichVu1 previousValue = this._DichVu1.Entity;
				if (((previousValue != value) 
							|| (this._DichVu1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DichVu1.Entity = null;
						previousValue.DichVu_Ves.Remove(this);
					}
					this._DichVu1.Entity = value;
					if ((value != null))
					{
						value.DichVu_Ves.Add(this);
						this._IDDichVu = value.IDDichVu;
					}
					else
					{
						this._IDDichVu = default(string);
					}
					this.SendPropertyChanged("DichVu1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ve_DichVu_Ve", Storage="_Ve", ThisKey="IDVe", OtherKey="IDVe", IsForeignKey=true)]
		public Ve Ve
		{
			get
			{
				return this._Ve.Entity;
			}
			set
			{
				Ve previousValue = this._Ve.Entity;
				if (((previousValue != value) 
							|| (this._Ve.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ve.Entity = null;
						previousValue.DichVu_Ves.Remove(this);
					}
					this._Ve.Entity = value;
					if ((value != null))
					{
						value.DichVu_Ves.Add(this);
						this._IDVe = value.IDVe;
					}
					else
					{
						this._IDVe = default(string);
					}
					this.SendPropertyChanged("Ve");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DichVu1")]
	public partial class DichVu1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDDichVu;
		
		private string _TenDichVu;
		
		private System.Nullable<double> _GiaTien;
		
		private EntitySet<DichVu_Ve> _DichVu_Ves;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDichVuChanging(string value);
    partial void OnIDDichVuChanged();
    partial void OnTenDichVuChanging(string value);
    partial void OnTenDichVuChanged();
    partial void OnGiaTienChanging(System.Nullable<double> value);
    partial void OnGiaTienChanged();
    #endregion
		
		public DichVu1()
		{
			this._DichVu_Ves = new EntitySet<DichVu_Ve>(new Action<DichVu_Ve>(this.attach_DichVu_Ves), new Action<DichVu_Ve>(this.detach_DichVu_Ves));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDichVu", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDDichVu
		{
			get
			{
				return this._IDDichVu;
			}
			set
			{
				if ((this._IDDichVu != value))
				{
					this.OnIDDichVuChanging(value);
					this.SendPropertyChanging();
					this._IDDichVu = value;
					this.SendPropertyChanged("IDDichVu");
					this.OnIDDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDichVu", DbType="NVarChar(50)")]
		public string TenDichVu
		{
			get
			{
				return this._TenDichVu;
			}
			set
			{
				if ((this._TenDichVu != value))
				{
					this.OnTenDichVuChanging(value);
					this.SendPropertyChanging();
					this._TenDichVu = value;
					this.SendPropertyChanged("TenDichVu");
					this.OnTenDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="Float")]
		public System.Nullable<double> GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu1_DichVu_Ve", Storage="_DichVu_Ves", ThisKey="IDDichVu", OtherKey="IDDichVu")]
		public EntitySet<DichVu_Ve> DichVu_Ves
		{
			get
			{
				return this._DichVu_Ves;
			}
			set
			{
				this._DichVu_Ves.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DichVu_Ves(DichVu_Ve entity)
		{
			this.SendPropertyChanging();
			entity.DichVu1 = this;
		}
		
		private void detach_DichVu_Ves(DichVu_Ve entity)
		{
			this.SendPropertyChanging();
			entity.DichVu1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDHoaDon;
		
		private string _TenHoaDon;
		
		private System.Nullable<double> _TongTien;
		
		private string _GhiChu;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _IDVe;
		
		private EntityRef<Ve> _Ve;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHoaDonChanging(string value);
    partial void OnIDHoaDonChanged();
    partial void OnTenHoaDonChanging(string value);
    partial void OnTenHoaDonChanged();
    partial void OnTongTienChanging(System.Nullable<double> value);
    partial void OnTongTienChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnIDVeChanging(string value);
    partial void OnIDVeChanged();
    #endregion
		
		public HoaDon()
		{
			this._Ve = default(EntityRef<Ve>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHoaDon", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDHoaDon
		{
			get
			{
				return this._IDHoaDon;
			}
			set
			{
				if ((this._IDHoaDon != value))
				{
					this.OnIDHoaDonChanging(value);
					this.SendPropertyChanging();
					this._IDHoaDon = value;
					this.SendPropertyChanged("IDHoaDon");
					this.OnIDHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHoaDon", DbType="NVarChar(50)")]
		public string TenHoaDon
		{
			get
			{
				return this._TenHoaDon;
			}
			set
			{
				if ((this._TenHoaDon != value))
				{
					this.OnTenHoaDonChanging(value);
					this.SendPropertyChanging();
					this._TenHoaDon = value;
					this.SendPropertyChanged("TenHoaDon");
					this.OnTenHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Float")]
		public System.Nullable<double> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDVe", DbType="NVarChar(50)")]
		public string IDVe
		{
			get
			{
				return this._IDVe;
			}
			set
			{
				if ((this._IDVe != value))
				{
					if (this._Ve.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDVeChanging(value);
					this.SendPropertyChanging();
					this._IDVe = value;
					this.SendPropertyChanged("IDVe");
					this.OnIDVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ve_HoaDon", Storage="_Ve", ThisKey="IDVe", OtherKey="IDVe", IsForeignKey=true)]
		public Ve Ve
		{
			get
			{
				return this._Ve.Entity;
			}
			set
			{
				Ve previousValue = this._Ve.Entity;
				if (((previousValue != value) 
							|| (this._Ve.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ve.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._Ve.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._IDVe = value.IDVe;
					}
					else
					{
						this._IDVe = default(string);
					}
					this.SendPropertyChanged("Ve");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDNguoiDung;
		
		private string _TenNguoiDung;
		
		private string _TenChucVu;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private string _UserName;
		
		private string _HashPass;
		
		private string _Quyen;
		
		private EntitySet<BinhLuan> _BinhLuans;
		
		private EntitySet<Ve> _Ves;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDNguoiDungChanging(string value);
    partial void OnIDNguoiDungChanged();
    partial void OnTenNguoiDungChanging(string value);
    partial void OnTenNguoiDungChanged();
    partial void OnTenChucVuChanging(string value);
    partial void OnTenChucVuChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnHashPassChanging(string value);
    partial void OnHashPassChanged();
    partial void OnQuyenChanging(string value);
    partial void OnQuyenChanged();
    #endregion
		
		public NguoiDung()
		{
			this._BinhLuans = new EntitySet<BinhLuan>(new Action<BinhLuan>(this.attach_BinhLuans), new Action<BinhLuan>(this.detach_BinhLuans));
			this._Ves = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves), new Action<Ve>(this.detach_Ves));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNguoiDung", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDNguoiDung
		{
			get
			{
				return this._IDNguoiDung;
			}
			set
			{
				if ((this._IDNguoiDung != value))
				{
					this.OnIDNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._IDNguoiDung = value;
					this.SendPropertyChanged("IDNguoiDung");
					this.OnIDNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiDung", DbType="NVarChar(50)")]
		public string TenNguoiDung
		{
			get
			{
				return this._TenNguoiDung;
			}
			set
			{
				if ((this._TenNguoiDung != value))
				{
					this.OnTenNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiDung = value;
					this.SendPropertyChanged("TenNguoiDung");
					this.OnTenNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChucVu", DbType="NVarChar(50)")]
		public string TenChucVu
		{
			get
			{
				return this._TenChucVu;
			}
			set
			{
				if ((this._TenChucVu != value))
				{
					this.OnTenChucVuChanging(value);
					this.SendPropertyChanging();
					this._TenChucVu = value;
					this.SendPropertyChanged("TenChucVu");
					this.OnTenChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(15)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HashPass", DbType="NVarChar(50)")]
		public string HashPass
		{
			get
			{
				return this._HashPass;
			}
			set
			{
				if ((this._HashPass != value))
				{
					this.OnHashPassChanging(value);
					this.SendPropertyChanging();
					this._HashPass = value;
					this.SendPropertyChanged("HashPass");
					this.OnHashPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="NChar(10)")]
		public string Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_BinhLuan", Storage="_BinhLuans", ThisKey="IDNguoiDung", OtherKey="IDNguoiDung")]
		public EntitySet<BinhLuan> BinhLuans
		{
			get
			{
				return this._BinhLuans;
			}
			set
			{
				this._BinhLuans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_Ve", Storage="_Ves", ThisKey="IDNguoiDung", OtherKey="IDNguoiDung")]
		public EntitySet<Ve> Ves
		{
			get
			{
				return this._Ves;
			}
			set
			{
				this._Ves.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phim")]
	public partial class Phim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDPhim;
		
		private string _TenPhim;
		
		private string _TheLoai;
		
		private System.Nullable<int> _ThoiLuong;
		
		private System.Nullable<System.DateTime> _KhoiChieu;
		
		private string _NamSanXuat;
		
		private string _DaoDien;
		
		private string _DienVien;
		
		private EntitySet<BinhLuan> _BinhLuans;
		
		private EntitySet<SuatChieu> _SuatChieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPhimChanging(string value);
    partial void OnIDPhimChanged();
    partial void OnTenPhimChanging(string value);
    partial void OnTenPhimChanged();
    partial void OnTheLoaiChanging(string value);
    partial void OnTheLoaiChanged();
    partial void OnThoiLuongChanging(System.Nullable<int> value);
    partial void OnThoiLuongChanged();
    partial void OnKhoiChieuChanging(System.Nullable<System.DateTime> value);
    partial void OnKhoiChieuChanged();
    partial void OnNamSanXuatChanging(string value);
    partial void OnNamSanXuatChanged();
    partial void OnDaoDienChanging(string value);
    partial void OnDaoDienChanged();
    partial void OnDienVienChanging(string value);
    partial void OnDienVienChanged();
    #endregion
		
		public Phim()
		{
			this._BinhLuans = new EntitySet<BinhLuan>(new Action<BinhLuan>(this.attach_BinhLuans), new Action<BinhLuan>(this.detach_BinhLuans));
			this._SuatChieus = new EntitySet<SuatChieu>(new Action<SuatChieu>(this.attach_SuatChieus), new Action<SuatChieu>(this.detach_SuatChieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPhim", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDPhim
		{
			get
			{
				return this._IDPhim;
			}
			set
			{
				if ((this._IDPhim != value))
				{
					this.OnIDPhimChanging(value);
					this.SendPropertyChanging();
					this._IDPhim = value;
					this.SendPropertyChanged("IDPhim");
					this.OnIDPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhim", DbType="NVarChar(50)")]
		public string TenPhim
		{
			get
			{
				return this._TenPhim;
			}
			set
			{
				if ((this._TenPhim != value))
				{
					this.OnTenPhimChanging(value);
					this.SendPropertyChanging();
					this._TenPhim = value;
					this.SendPropertyChanged("TenPhim");
					this.OnTenPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheLoai", DbType="NVarChar(50)")]
		public string TheLoai
		{
			get
			{
				return this._TheLoai;
			}
			set
			{
				if ((this._TheLoai != value))
				{
					this.OnTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._TheLoai = value;
					this.SendPropertyChanged("TheLoai");
					this.OnTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiLuong", DbType="Int")]
		public System.Nullable<int> ThoiLuong
		{
			get
			{
				return this._ThoiLuong;
			}
			set
			{
				if ((this._ThoiLuong != value))
				{
					this.OnThoiLuongChanging(value);
					this.SendPropertyChanging();
					this._ThoiLuong = value;
					this.SendPropertyChanged("ThoiLuong");
					this.OnThoiLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoiChieu", DbType="Date")]
		public System.Nullable<System.DateTime> KhoiChieu
		{
			get
			{
				return this._KhoiChieu;
			}
			set
			{
				if ((this._KhoiChieu != value))
				{
					this.OnKhoiChieuChanging(value);
					this.SendPropertyChanging();
					this._KhoiChieu = value;
					this.SendPropertyChanged("KhoiChieu");
					this.OnKhoiChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSanXuat", DbType="NVarChar(50)")]
		public string NamSanXuat
		{
			get
			{
				return this._NamSanXuat;
			}
			set
			{
				if ((this._NamSanXuat != value))
				{
					this.OnNamSanXuatChanging(value);
					this.SendPropertyChanging();
					this._NamSanXuat = value;
					this.SendPropertyChanged("NamSanXuat");
					this.OnNamSanXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaoDien", DbType="NVarChar(50)")]
		public string DaoDien
		{
			get
			{
				return this._DaoDien;
			}
			set
			{
				if ((this._DaoDien != value))
				{
					this.OnDaoDienChanging(value);
					this.SendPropertyChanging();
					this._DaoDien = value;
					this.SendPropertyChanged("DaoDien");
					this.OnDaoDienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienVien", DbType="NVarChar(50)")]
		public string DienVien
		{
			get
			{
				return this._DienVien;
			}
			set
			{
				if ((this._DienVien != value))
				{
					this.OnDienVienChanging(value);
					this.SendPropertyChanging();
					this._DienVien = value;
					this.SendPropertyChanged("DienVien");
					this.OnDienVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_BinhLuan", Storage="_BinhLuans", ThisKey="IDPhim", OtherKey="IDPhim")]
		public EntitySet<BinhLuan> BinhLuans
		{
			get
			{
				return this._BinhLuans;
			}
			set
			{
				this._BinhLuans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_SuatChieu", Storage="_SuatChieus", ThisKey="IDPhim", OtherKey="IDPhim")]
		public EntitySet<SuatChieu> SuatChieus
		{
			get
			{
				return this._SuatChieus;
			}
			set
			{
				this._SuatChieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.Phim = this;
		}
		
		private void detach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.Phim = null;
		}
		
		private void attach_SuatChieus(SuatChieu entity)
		{
			this.SendPropertyChanging();
			entity.Phim = this;
		}
		
		private void detach_SuatChieus(SuatChieu entity)
		{
			this.SendPropertyChanging();
			entity.Phim = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongChieu")]
	public partial class PhongChieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDPhongChieu;
		
		private string _TenPhongChieu;
		
		private string _LoaiPhong;
		
		private EntitySet<SuatChieu> _SuatChieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPhongChieuChanging(string value);
    partial void OnIDPhongChieuChanged();
    partial void OnTenPhongChieuChanging(string value);
    partial void OnTenPhongChieuChanged();
    partial void OnLoaiPhongChanging(string value);
    partial void OnLoaiPhongChanged();
    #endregion
		
		public PhongChieu()
		{
			this._SuatChieus = new EntitySet<SuatChieu>(new Action<SuatChieu>(this.attach_SuatChieus), new Action<SuatChieu>(this.detach_SuatChieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPhongChieu", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDPhongChieu
		{
			get
			{
				return this._IDPhongChieu;
			}
			set
			{
				if ((this._IDPhongChieu != value))
				{
					this.OnIDPhongChieuChanging(value);
					this.SendPropertyChanging();
					this._IDPhongChieu = value;
					this.SendPropertyChanged("IDPhongChieu");
					this.OnIDPhongChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhongChieu", DbType="NVarChar(50)")]
		public string TenPhongChieu
		{
			get
			{
				return this._TenPhongChieu;
			}
			set
			{
				if ((this._TenPhongChieu != value))
				{
					this.OnTenPhongChieuChanging(value);
					this.SendPropertyChanging();
					this._TenPhongChieu = value;
					this.SendPropertyChanged("TenPhongChieu");
					this.OnTenPhongChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiPhong", DbType="NVarChar(50)")]
		public string LoaiPhong
		{
			get
			{
				return this._LoaiPhong;
			}
			set
			{
				if ((this._LoaiPhong != value))
				{
					this.OnLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._LoaiPhong = value;
					this.SendPropertyChanged("LoaiPhong");
					this.OnLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongChieu_SuatChieu", Storage="_SuatChieus", ThisKey="IDPhongChieu", OtherKey="IDPhongChieu")]
		public EntitySet<SuatChieu> SuatChieus
		{
			get
			{
				return this._SuatChieus;
			}
			set
			{
				this._SuatChieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SuatChieus(SuatChieu entity)
		{
			this.SendPropertyChanging();
			entity.PhongChieu = this;
		}
		
		private void detach_SuatChieus(SuatChieu entity)
		{
			this.SendPropertyChanging();
			entity.PhongChieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SuatChieu")]
	public partial class SuatChieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDSuatChieu;
		
		private string _TenSuatChieu;
		
		private System.Nullable<System.DateTime> _NgayChieu;
		
		private System.Nullable<int> _ThoiGianChieu;
		
		private string _IDPhongChieu;
		
		private string _IDPhim;
		
		private EntitySet<Ve> _Ves;
		
		private EntityRef<Phim> _Phim;
		
		private EntityRef<PhongChieu> _PhongChieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDSuatChieuChanging(string value);
    partial void OnIDSuatChieuChanged();
    partial void OnTenSuatChieuChanging(string value);
    partial void OnTenSuatChieuChanged();
    partial void OnNgayChieuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChieuChanged();
    partial void OnThoiGianChieuChanging(System.Nullable<int> value);
    partial void OnThoiGianChieuChanged();
    partial void OnIDPhongChieuChanging(string value);
    partial void OnIDPhongChieuChanged();
    partial void OnIDPhimChanging(string value);
    partial void OnIDPhimChanged();
    #endregion
		
		public SuatChieu()
		{
			this._Ves = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves), new Action<Ve>(this.detach_Ves));
			this._Phim = default(EntityRef<Phim>);
			this._PhongChieu = default(EntityRef<PhongChieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSuatChieu", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDSuatChieu
		{
			get
			{
				return this._IDSuatChieu;
			}
			set
			{
				if ((this._IDSuatChieu != value))
				{
					this.OnIDSuatChieuChanging(value);
					this.SendPropertyChanging();
					this._IDSuatChieu = value;
					this.SendPropertyChanged("IDSuatChieu");
					this.OnIDSuatChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSuatChieu", DbType="NVarChar(50)")]
		public string TenSuatChieu
		{
			get
			{
				return this._TenSuatChieu;
			}
			set
			{
				if ((this._TenSuatChieu != value))
				{
					this.OnTenSuatChieuChanging(value);
					this.SendPropertyChanging();
					this._TenSuatChieu = value;
					this.SendPropertyChanged("TenSuatChieu");
					this.OnTenSuatChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChieu", DbType="Date")]
		public System.Nullable<System.DateTime> NgayChieu
		{
			get
			{
				return this._NgayChieu;
			}
			set
			{
				if ((this._NgayChieu != value))
				{
					this.OnNgayChieuChanging(value);
					this.SendPropertyChanging();
					this._NgayChieu = value;
					this.SendPropertyChanged("NgayChieu");
					this.OnNgayChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianChieu", DbType="Int")]
		public System.Nullable<int> ThoiGianChieu
		{
			get
			{
				return this._ThoiGianChieu;
			}
			set
			{
				if ((this._ThoiGianChieu != value))
				{
					this.OnThoiGianChieuChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianChieu = value;
					this.SendPropertyChanged("ThoiGianChieu");
					this.OnThoiGianChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPhongChieu", DbType="NChar(10)")]
		public string IDPhongChieu
		{
			get
			{
				return this._IDPhongChieu;
			}
			set
			{
				if ((this._IDPhongChieu != value))
				{
					if (this._PhongChieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDPhongChieuChanging(value);
					this.SendPropertyChanging();
					this._IDPhongChieu = value;
					this.SendPropertyChanged("IDPhongChieu");
					this.OnIDPhongChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPhim", DbType="NVarChar(50)")]
		public string IDPhim
		{
			get
			{
				return this._IDPhim;
			}
			set
			{
				if ((this._IDPhim != value))
				{
					if (this._Phim.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDPhimChanging(value);
					this.SendPropertyChanging();
					this._IDPhim = value;
					this.SendPropertyChanged("IDPhim");
					this.OnIDPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SuatChieu_Ve", Storage="_Ves", ThisKey="IDSuatChieu", OtherKey="IDSuatChieu")]
		public EntitySet<Ve> Ves
		{
			get
			{
				return this._Ves;
			}
			set
			{
				this._Ves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_SuatChieu", Storage="_Phim", ThisKey="IDPhim", OtherKey="IDPhim", IsForeignKey=true)]
		public Phim Phim
		{
			get
			{
				return this._Phim.Entity;
			}
			set
			{
				Phim previousValue = this._Phim.Entity;
				if (((previousValue != value) 
							|| (this._Phim.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phim.Entity = null;
						previousValue.SuatChieus.Remove(this);
					}
					this._Phim.Entity = value;
					if ((value != null))
					{
						value.SuatChieus.Add(this);
						this._IDPhim = value.IDPhim;
					}
					else
					{
						this._IDPhim = default(string);
					}
					this.SendPropertyChanged("Phim");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongChieu_SuatChieu", Storage="_PhongChieu", ThisKey="IDPhongChieu", OtherKey="IDPhongChieu", IsForeignKey=true)]
		public PhongChieu PhongChieu
		{
			get
			{
				return this._PhongChieu.Entity;
			}
			set
			{
				PhongChieu previousValue = this._PhongChieu.Entity;
				if (((previousValue != value) 
							|| (this._PhongChieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongChieu.Entity = null;
						previousValue.SuatChieus.Remove(this);
					}
					this._PhongChieu.Entity = value;
					if ((value != null))
					{
						value.SuatChieus.Add(this);
						this._IDPhongChieu = value.IDPhongChieu;
					}
					else
					{
						this._IDPhongChieu = default(string);
					}
					this.SendPropertyChanged("PhongChieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.SuatChieu = this;
		}
		
		private void detach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.SuatChieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ve")]
	public partial class Ve : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDVe;
		
		private string _TenVe;
		
		private System.Nullable<double> _GiaVe;
		
		private string _TrangThai;
		
		private string _IDChoNgoi;
		
		private string _IDSuatChieu;
		
		private string _IDNguoiDung;
		
		private EntitySet<DichVu_Ve> _DichVu_Ves;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntityRef<ChoNgoi1> _ChoNgoi1;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
		private EntityRef<SuatChieu> _SuatChieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDVeChanging(string value);
    partial void OnIDVeChanged();
    partial void OnTenVeChanging(string value);
    partial void OnTenVeChanged();
    partial void OnGiaVeChanging(System.Nullable<double> value);
    partial void OnGiaVeChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnIDChoNgoiChanging(string value);
    partial void OnIDChoNgoiChanged();
    partial void OnIDSuatChieuChanging(string value);
    partial void OnIDSuatChieuChanged();
    partial void OnIDNguoiDungChanging(string value);
    partial void OnIDNguoiDungChanged();
    #endregion
		
		public Ve()
		{
			this._DichVu_Ves = new EntitySet<DichVu_Ve>(new Action<DichVu_Ve>(this.attach_DichVu_Ves), new Action<DichVu_Ve>(this.detach_DichVu_Ves));
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._ChoNgoi1 = default(EntityRef<ChoNgoi1>);
			this._NguoiDung = default(EntityRef<NguoiDung>);
			this._SuatChieu = default(EntityRef<SuatChieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDVe", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDVe
		{
			get
			{
				return this._IDVe;
			}
			set
			{
				if ((this._IDVe != value))
				{
					this.OnIDVeChanging(value);
					this.SendPropertyChanging();
					this._IDVe = value;
					this.SendPropertyChanged("IDVe");
					this.OnIDVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVe", DbType="NVarChar(50)")]
		public string TenVe
		{
			get
			{
				return this._TenVe;
			}
			set
			{
				if ((this._TenVe != value))
				{
					this.OnTenVeChanging(value);
					this.SendPropertyChanging();
					this._TenVe = value;
					this.SendPropertyChanged("TenVe");
					this.OnTenVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaVe", DbType="Float")]
		public System.Nullable<double> GiaVe
		{
			get
			{
				return this._GiaVe;
			}
			set
			{
				if ((this._GiaVe != value))
				{
					this.OnGiaVeChanging(value);
					this.SendPropertyChanging();
					this._GiaVe = value;
					this.SendPropertyChanged("GiaVe");
					this.OnGiaVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChoNgoi", DbType="NVarChar(50)")]
		public string IDChoNgoi
		{
			get
			{
				return this._IDChoNgoi;
			}
			set
			{
				if ((this._IDChoNgoi != value))
				{
					if (this._ChoNgoi1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChoNgoiChanging(value);
					this.SendPropertyChanging();
					this._IDChoNgoi = value;
					this.SendPropertyChanged("IDChoNgoi");
					this.OnIDChoNgoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSuatChieu", DbType="NVarChar(50)")]
		public string IDSuatChieu
		{
			get
			{
				return this._IDSuatChieu;
			}
			set
			{
				if ((this._IDSuatChieu != value))
				{
					if (this._SuatChieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDSuatChieuChanging(value);
					this.SendPropertyChanging();
					this._IDSuatChieu = value;
					this.SendPropertyChanged("IDSuatChieu");
					this.OnIDSuatChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNguoiDung", DbType="NVarChar(50)")]
		public string IDNguoiDung
		{
			get
			{
				return this._IDNguoiDung;
			}
			set
			{
				if ((this._IDNguoiDung != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._IDNguoiDung = value;
					this.SendPropertyChanged("IDNguoiDung");
					this.OnIDNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ve_DichVu_Ve", Storage="_DichVu_Ves", ThisKey="IDVe", OtherKey="IDVe")]
		public EntitySet<DichVu_Ve> DichVu_Ves
		{
			get
			{
				return this._DichVu_Ves;
			}
			set
			{
				this._DichVu_Ves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ve_HoaDon", Storage="_HoaDons", ThisKey="IDVe", OtherKey="IDVe")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChoNgoi1_Ve", Storage="_ChoNgoi1", ThisKey="IDChoNgoi", OtherKey="IDChoNgoi", IsForeignKey=true)]
		public ChoNgoi1 ChoNgoi1
		{
			get
			{
				return this._ChoNgoi1.Entity;
			}
			set
			{
				ChoNgoi1 previousValue = this._ChoNgoi1.Entity;
				if (((previousValue != value) 
							|| (this._ChoNgoi1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChoNgoi1.Entity = null;
						previousValue.Ves.Remove(this);
					}
					this._ChoNgoi1.Entity = value;
					if ((value != null))
					{
						value.Ves.Add(this);
						this._IDChoNgoi = value.IDChoNgoi;
					}
					else
					{
						this._IDChoNgoi = default(string);
					}
					this.SendPropertyChanged("ChoNgoi1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_Ve", Storage="_NguoiDung", ThisKey="IDNguoiDung", OtherKey="IDNguoiDung", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.Ves.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.Ves.Add(this);
						this._IDNguoiDung = value.IDNguoiDung;
					}
					else
					{
						this._IDNguoiDung = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SuatChieu_Ve", Storage="_SuatChieu", ThisKey="IDSuatChieu", OtherKey="IDSuatChieu", IsForeignKey=true)]
		public SuatChieu SuatChieu
		{
			get
			{
				return this._SuatChieu.Entity;
			}
			set
			{
				SuatChieu previousValue = this._SuatChieu.Entity;
				if (((previousValue != value) 
							|| (this._SuatChieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SuatChieu.Entity = null;
						previousValue.Ves.Remove(this);
					}
					this._SuatChieu.Entity = value;
					if ((value != null))
					{
						value.Ves.Add(this);
						this._IDSuatChieu = value.IDSuatChieu;
					}
					else
					{
						this._IDSuatChieu = default(string);
					}
					this.SendPropertyChanged("SuatChieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DichVu_Ves(DichVu_Ve entity)
		{
			this.SendPropertyChanging();
			entity.Ve = this;
		}
		
		private void detach_DichVu_Ves(DichVu_Ve entity)
		{
			this.SendPropertyChanging();
			entity.Ve = null;
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Ve = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Ve = null;
		}
	}
}
#pragma warning restore 1591
