//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlyrapchieuphim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ve()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.DichVu1 = new HashSet<DichVu1>();
        }
    
        public string IDVe { get; set; }
        public string TenVe { get; set; }
        public Nullable<double> GiaVe { get; set; }
        public string TrangThai { get; set; }
        public string IDChoNgoi { get; set; }
        public string IDSuatChieu { get; set; }
        public string IDNguoiDung { get; set; }
    
        public virtual ChoNgoi1 ChoNgoi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SuatChieu SuatChieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVu1> DichVu1 { get; set; }
    }
}
